---
- name: Configure Workstation for personal usage
  hosts: all
  become: false
  become_user: root
  vars:
    packages_to_install:
      - podman
        #- python3-molecule
  tasks:
    - name: enable EPEL Repository
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: installed
        disable_gpg_check: true
      become: true

    - name: Install snapd
      ansible.builtin.yum:
        name: snapd
        state: installed
      become: true

    - name: Enable snapd socket
      ansible.builtin.service:
        name: snapd.socket
        state: started
        enabled: true
      become: true

    - name: Template out .bashrc
      ansible.builtin.template:
        src: bashrc.j2
        dest: "${HOME}/.bashrc"
        
    - name: Template out .gitconfig
      ansible.builtin.template:
        src: gitconfig.j2
        dest: "${HOME}/.gitconfig"
        
    - name: Install packages
      ansible.builtin.yum:
        name: "{{ packages_to_install }}"
        state: installed
      become: true
